allow-command-blocks: false
chat-commands:
  # Unprefixed
  - w
  - me
  - tm
  - msg
  - say
  - tell
  - whisper
  - teammsg
  # Minecraft
  - minecraft:w
  - minecraft:me
  - minecraft:tm
  - minecraft:msg
  - minecraft:say
  - minecraft:tell
  - minecraft:teammsg
  # Essentials
  - ew
  - eme
  - emsg
  - esay
  - etell
  - ewhisper
  - essentials:w
  - essentials:me
  - essentials:msg
  - essentials:say
  - essentials:tell
  - essentials:whisper
  - essentials:ew
  - essentials:eme
  - essentials:emsg
  - essentials:esay
  - essentials:etell
  - essentials:ewhisper
